version: "3.0"
services:
  backend:
    image: mateusofdata/apirotulo
    container_name: backend_app
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - shared-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - shared-network

  frontend:
    image: mateusofdata/frontendrotulo
    ports:
      - "${FRONTEND_PORT}:${NGINX_PORT}"
    restart: always
    networks:
      - shared-network

networks:
  shared-network:

volumes:
  mysql_data:
